[New sample] Display OGC API collection
Esri/arcgis-runtime-samples-android pull request #891
Opened 2021-06-23 14:18 UTC by shubham7109

2021-06-23 15:02 UTC, TADraeseke requested changes
Thanks @shubham7109 - This is a clean and very readable sample! Nice work!

Just a few small bits commented in line.

2021-06-23 16:17 UTC, TADraeseke commented on kotlin/display-ogc-api-collection/src/main/java/com/esri/arcgisruntime/sample/displayogcapicollection/MainActivity.kt
> +                visibleExtentQuery.maxFeatures = 5000
```suggestion
                val visibleExtentQuery = QueryParameters().apply {
               geometry = currentExtent
                spatialRelationship =
                    QueryParameters.SpatialRelationship.INTERSECTS
                // set a limit of 5000 on the number of returned features per request, the default on some services
                // could be as low as 10
                maxFeatures = 5000
                }
```

Just spotted a good opportunity to use a scoping function here :)

2021-06-24 19:19 UTC, shubham7109 commented
- Resolved PR suggestions
- Added SC image
- Added `README.metadata.json` file
- Need input for `provision_from` & `provision_to` fields.

2021-06-25 13:16 UTC, TADraeseke approved these changes
Just a few small things, then I think you're good to merge. Thanks @shubham7109!

2021-06-25 13:16 UTC, TADraeseke commented on kotlin/display-ogc-api-collection/README.metadata.json
> +    "category": "TODO",
```suggestion
    "category": "Layers",
```

2021-06-25 13:16 UTC, TADraeseke commented on kotlin/display-ogc-api-collection/README.metadata.json
> +    "provision_to": "TODO",
```suggestion
```

2021-06-25 13:16 UTC, TADraeseke commented on kotlin/display-ogc-api-collection/build.gradle
> +
```suggestion
```

2021-06-25 13:16 UTC, TADraeseke commented on kotlin/display-ogc-api-collection/src/main/java/com/esri/arcgisruntime/sample/displayogcapicollection/MainActivity.kt
> +    // via OgcFeatureCollectionInfo.getCollectionId().
```suggestion
    // via OgcFeatureCollectionInfo.getCollectionId()
```

2021-06-29 21:48 UTC, merged