New sample: NMEA Location Data Source
Esri/arcgis-runtime-samples-android pull request #917
Opened 2021-09-08 21:16 UTC by shubham7109

This sample demonstrates how to parse NMEA sentences and use the results to show device location on the map.

2021-09-10 04:49 UTC, sorenoid requested changes
Hi @shubham7109 very nice work! I have two small issues, one cosmetic, the other a critical fix to the path to push the nmea file to the device.

2021-09-10 04:49 UTC, sorenoid commented on kotlin/display-device-location-with-nmea-data-sources/README.md
> +`adb push Redlands.nmea /Android/data/com.esri.arcgisruntime.sample.displaydevicelocationwithnmeadatasources/files/dodge_city.vtpk`
```suggestion
`adb push Redlands.nmea /sdcard/Android/data/com.esri.arcgisruntime.sample.displaydevicelocationwithnmeadatasources/files/Redlands.nmea`
```

2021-09-10 04:49 UTC, sorenoid commented on kotlin/display-device-location-with-nmea-data-sources/src/main/java/com/esri/arcgisruntime/sample/displaydevicelocationwithnmeadatasources/MainActivity.kt
> +                    accuracyTV.text = "Accuracy- Horizontal: %.1fft, Vertical: %.1ft".format(
```suggestion
                    accuracyTV.text = "Accuracy- Horizontal: %.1fft, Vertical: %.1fft".format(
```

2021-09-10 17:53 UTC, shubham7109 commented
Thanks for the catch Soren! I have gone ahead and added those changes.

2021-09-14 17:20 UTC, sorenoid approved these changes
👍  looks good @shubham7109

2021-09-14 19:08 UTC, merged