initialize address finding only once map has loaded
Esri/arcgis-runtime-samples-android pull request #929
Opened 2021-11-26 10:43 UTC by gunt0001

2021-12-08 10:54 UTC, fpearson1111 commented
I also added some commits:
- prevent the callout from showing until the async viewpoint setting operation completes -- seems like showing the callout cancels the viewpoint setting operation
- don't show the callout if it's already being shown -- this stops the callout animation from playing when the callout is already active, which looks "unnatural"

2021-12-09 12:55 UTC, TADraeseke requested changes
Thanks guys! Just one small suggestion.

We should also change the Java version of this sample if we're changing the behaviour in the Kotlin sample.

2021-12-09 12:55 UTC, TADraeseke commented on kotlin/find-address/src/main/java/com/esri/arcgisruntime/sample/findaddress/MainActivity.kt
> +        Toast.makeText(applicationContext, "Map failed to load", Toast.LENGTH_LONG).show()
```suggestion
                Log.e(TAG, "Map failed to load: " + topographicMap.loadError.message)
                Toast.makeText(
                    applicationContext,
                    "Map failed to load: " + topographicMap.loadError.message,
                    Toast.LENGTH_LONG
                ).show()
```

2021-12-10 09:11 UTC, fpearson1111 commented
Thanks @TADraeseke, I made that change, can you take another look please?

2022-01-19 22:55 UTC, shubham7109 approved these changes
I've added the Java sample changes, and the Kotlin sample looks good! Could you take a look at this? @TADraeseke

2022-01-20 14:54 UTC, saratchandrakarumuri approved these changes
Tested both Java and Kotlin samples and correct viewpoints are set for search results as expected with this fix.

2022-01-20 15:12 UTC, TADraeseke approved these changes
LGTM! Thanks @shubham7109

2022-01-20 16:43 UTC, merged