U13 fixes
Esri/arcgis-runtime-samples-android pull request #942
Opened 2021-12-21 00:59 UTC by shubham7109

This PR fixes the following errors:
- [x] Edit attachments: Delete confirmation buttons is not displayed
- [x] Edit with branch versioning: App crashes when the branch already exists instead of throwing error or warning
- [x] Generate offline map with local basemap: Selecting no to local basemap, retrieves an error message and job is not started 
- [x] Query map image sublayer: Query button was disabled

2021-12-21 10:14 UTC, TADraeseke requested changes
Nice job fixing these. Just a few small comments below. Thanks @shubham7109!

2021-12-21 10:14 UTC, TADraeseke commented on kotlin/edit-with-branch-versioning/src/main/java/com/esri/arcgisruntime/sample/editwithbranchversioning/MainActivity.kt
> +        try{
```suggestion
        try {
```

2021-12-21 10:14 UTC, TADraeseke commented on kotlin/edit-with-branch-versioning/src/main/java/com/esri/arcgisruntime/sample/editwithbranchversioning/MainActivity.kt
> +            }catch (e: java.lang.Exception){
```suggestion
            } catch (e: java.lang.Exception) {
```

2021-12-21 10:14 UTC, TADraeseke commented on kotlin/edit-with-branch-versioning/src/main/java/com/esri/arcgisruntime/sample/editwithbranchversioning/MainActivity.kt
> +            Toast.makeText(this, e.message.toString(),Toast.LENGTH_SHORT).show()
Could be good to prepend with some plain English explanation of what might have gone wrong here. "Error getting service info: " + e.message, or something like that

2021-12-21 17:03 UTC, shubham7109 commented
Thanks Trevor for the feedback, I've gone ahead and added the  changes in!

2021-12-22 15:58 UTC, TADraeseke approved these changes
LGTM! Just one small formatting thing below. Thanks @shubham7109!

2021-12-22 16:02 UTC, merged