Update README.md
Esri/arcgis-runtime-samples-android pull request #948
Opened 2022-01-27 10:38 UTC by TADraeseke

Hi @markjdugger -- can you review and comment if you think this is clearer? Thanks!

2022-01-27 20:56 UTC, markjdugger requested changes

2022-01-27 20:56 UTC, markjdugger commented on README.md
> +* From the toolbar select **File > Open**, or **Open** from the Welcome Quick Start.
```suggestion
* From the Welcome to Android Studio screen, click the **Open** button. (If you're already inside a project, click **File > Open** in the menu bar instead.)
```

2022-01-27 20:56 UTC, markjdugger commented on README.md
> +* Navigate to **arcgis-runtime-samples-android/java** or **arcgis-runtime-samples-android/kotlin** project folder,  directory and click **OK**
```suggestion
* Navigate to the **arcgis-runtime-samples-android/java** or **arcgis-runtime-samples-android/kotlin** folder and click **OK**.
```

2022-01-27 20:59 UTC, markjdugger commented
@TADraeseke I made edit suggestions above. I matched the wording with what we are using in the Android tutorials. (The Android tutorial changes are not merged yet, but you can see what we intend by examining the modified Java tutorials, already on the public website:
- https://developers.arcgis.com/java/maps-2d/tutorials/display-a-map/#create-a-new-java-project-with-gradle

IntelliJ IDEA and Android Studio, both from JetBrains, have very similar UI, so it makes sense to use the same wording for both Java and Android.

2022-01-28 10:50 UTC, TADraeseke commented
Cool! I like you wording better. Made those changes.

2022-02-08 15:47 UTC, merged