Create and Save KML point symbols patch
Esri/arcgis-runtime-samples-android pull request #974
Opened 2022-04-18 21:14 UTC by shubham7109

## Description
`Create and Save KML` sample has an issue with the "Point Symbol" images not loading using a spinner adapter. Fixed by using Viewbinding on `getView()` instead of `createView()` 

## Links and Data
Sample Epic: `runtime/common-samples/issues/3452`

2022-04-18 21:30 UTC, saratchandrakarumuri approved these changes
All point symbols are now rendered as expected with this PR

2022-04-19 10:22 UTC, TADraeseke requested changes
Great to get this fixes and use GONE instead of invisible. UI looks cleaner.

The only thing is the bottom box now partly covers the attribution bar. I think either bump the UI box up or put it back in the upper right.

Thanks @shubham7109!

2022-04-19 15:59 UTC, shubham7109 commented
Bumped up the UI box to not block the attribution bar

2022-04-19 15:59 UTC, TADraeseke approved these changes
LGTM! Thanks @shubham7109!

2022-04-19 16:01 UTC, merged