Trev8939/set max extent
Esri/arcgis-runtime-samples-android pull request #976
Opened 2022-04-21 15:13 UTC by TADraeseke

Create a new sample demonstrating the new maxExtent property

2022-04-21 16:39 UTC, shubham7109 commented on kotlin/set-max-extent/README.metadata.json
> +        "/src/main/java/com/esri/arcgisruntime/sample/setmaxextent/MainActivity.kt"
```suggestion
        "src/main/java/com/esri/arcgisruntime/sample/setmaxextent/MainActivity.kt"
```

2022-04-21 17:41 UTC, shubham7109 requested changes
Just a minor change in the metadata file. 

One note, avoid screenshots with the attribute tab and the "Licensed for developer use", as they are not really helpful info to have in the sample-viewer screenshots. Also, crop the image to 700x400px rather than resize the image. This helps as the image does not feel "stretched"

2022-04-21 17:42 UTC, shubham7109 commented on kotlin/set-max-extent/README.metadata.json
> +    "category": "Maps and scenes",
```suggestion
    "category": "Maps and Scenes",
```
This is causing a crash while running it on the sample-viewer

2022-04-22 10:34 UTC, TADraeseke commented
Thanks @shubham7109! I've made those changes to the metadata file and added code to show the map's max extent as a red dotted outline.

I'm not sure we should be removing the attribution bar in the screenshot though, since the data is licensed, we're really not supposed to block or remove it.

2022-04-22 17:13 UTC, shubham7109 approved these changes
Looks good! We can better visualize the max extent behavior with the graphic now! 

Regarding the screenshots, that's a good point and could be worth a discussion with other platforms and maybe standardizing it.

2022-04-25 19:08 UTC, shubham7109 commented
I took a look at the seekbar approach for the sample and realized that it wouldn't really work well since `newEnvelope.expand` is not a linear change. Instead, it would work better with buttons.
![max_extent](https://user-images.githubusercontent.com/14892474/165157283-dcec38f8-29c4-4955-a4bd-d042f4c21736.gif)


I may have gone a little overboard with the design, but it would showcase the `map.maxExtent` property from a sample perspective with straightforward code implementation.

2022-04-25 23:26 UTC, saratchandrakarumuri approved these changes

2022-04-25 23:27 UTC, shubham7109 requested changes

2022-04-27 23:53 UTC, shubham7109 commented
Removed buttons and added a switch for `maxExtent` using the feedback from the review. The readme will probably need to be update to this

2022-04-28 17:52 UTC, shubham7109 approved these changes
Few readme change suggestions based on the toggle switch added to the sample.

2022-04-28 17:52 UTC, shubham7109 commented on kotlin/set-max-extent/README.md
> +by the max extent.
```suggestion
The application loads with a map whose maximum extent has been set to the borders of Colorado. Note
that you won't be able to pan far from the Colorado border or zoom out beyond the minimum scale set
by the max extent. Use the toggle switch to disable the max extent to freely pan/zoom around the map. 
```

2022-04-28 17:52 UTC, shubham7109 commented on kotlin/set-max-extent/README.md
> +3. Set the map to a `MapView` object.
```suggestion
3. Set the map to a `MapView` object.
4. Set `map.maxExtent = null` to disable the maximum extent of the map 
```

2022-04-28 17:52 UTC, shubham7109 commented on kotlin/set-max-extent/README.md
> +3. Set the map to a `MapView` object.
```suggestion
3. Set the map to a `MapView` object.
4. Set `map.maxExtent = null` to disable the maximum extent of the map 
```

2022-04-29 10:23 UTC, TADraeseke reviewed
Thanks for your work on this @shubham7109! Just couple small comments below!

2022-04-29 10:23 UTC, TADraeseke commented on kotlin/set-max-extent/src/main/res/layout/activity_main.xml
> +
```suggestion
        app:layout_constraintTop_toTopOf="parent" />

```

2022-04-29 10:23 UTC, TADraeseke commented on kotlin/set-max-extent/src/main/java/com/esri/arcgisruntime/sample/setmaxextent/MainActivity.kt
> +                coloradoMap.maxExtent = null
maybe on toggle we should set Text on the TextView to:

"Maximum extent enabled"

"Maximum extent disabled"

2022-04-29 10:23 UTC, TADraeseke commented on kotlin/set-max-extent/src/main/res/values/strings.xml
> +    <string name="extentText">Enable/Disable the maximum extent</string>
These can be removed

2022-05-03 13:49 UTC, TADraeseke commented
LGTM! Merge when ready @shubham7109!

2022-05-03 16:54 UTC, merged