Enhancements for Browse building floors sample
Esri/arcgis-runtime-samples-android pull request #982
Opened 2022-05-18 23:08 UTC by shubham7109

## Description
PR to support "vertical order" for the Browse building floors sample. Since buildings can have basements, the starting floor should be set to `verticalOrder == 0` instead of using `currentFloor = 0`.

Changes made:
- Removed hardcoded floors, now we use a spinner adapter to retrieve floor names `floorLevels[position].longName` 
- Added a spinner item layout file
- Added support to use `verticalOrder == 0` as the default floor on app launch, instead of the first floor in `floorManager.levels`

The sample will now be compatible with any floor-aware webmap! 

## Links and Data
Sample Epic: `runtime/common-samples/issues/3465`

## What To Review
-  Review the code to make sure it is easy to follow like other samples on Android
- The sample defaults to use `verticalOrder == 0` and can switch between other floors 

## How to Test
Run the sample on the sample viewer or the repo.

2022-05-23 21:10 UTC, shubham7109 commented on kotlin/browse-building-floors/src/main/java/com/esri/arcgisruntime/sample/browsebuildingfloors/MainActivity.kt
> +                    ))
Cool kotlin-y approach to resolve the default floor to the ground floor

2022-05-30 13:31 UTC, TADraeseke approved these changes
LGTM! Just a few small things @shubham7109!

2022-05-30 13:31 UTC, TADraeseke commented on kotlin/browse-building-floors/src/main/java/com/esri/arcgisruntime/sample/browsebuildingfloors/MainActivity.kt
> +                // set initial floor level to ground floor
I think this was better before. Remember we're trying to use the `apply` block as an extended builder.

someObject(some paramater).apply {
    someOtherParamater = blah
    yetSome Other = blah 2
}

Let's reserve things like .loadAsync() and .cancel() to calls to the parent object, just for readability

2022-05-30 13:31 UTC, TADraeseke commented on kotlin/browse-building-floors/src/main/res/layout/browse_floors_spinner_item.xml
> +    android:padding="10dp" />
missing new line after

2022-05-30 13:31 UTC, TADraeseke commented on kotlin/browse-building-floors/src/main/res/layout/browse_floors_spinner_item.xml
> +    android:padding="10dp" />
missing new line after

2022-05-30 20:41 UTC, hud10837 requested changes
A few questions/changes :)

2022-05-31 23:25 UTC, shubham7109 commented on kotlin/browse-building-floors/src/main/java/com/esri/arcgisruntime/sample/browsebuildingfloors/MainActivity.kt
> +     * Load and update the [floorManager] to the currently selected floor
Updated the function comment

2022-05-31 23:25 UTC, shubham7109 commented on kotlin/browse-building-floors/src/main/java/com/esri/arcgisruntime/sample/browsebuildingfloors/MainActivity.kt
>      private fun setFloor(floorManager: FloorManager) {
Good point, this was the approach used in another sample. Renamed to `initializeFloorSpinner`

2022-06-01 00:16 UTC, shubham7109 commented
Thanks for the detailed feedback @hud10837, ready for re-review 👍

2022-06-01 12:08 UTC, hud10837 approved these changes
👍 Looks great to me

2022-06-02 23:18 UTC, saratchandrakarumuri approved these changes
sample is working as expected

2022-06-06 16:20 UTC, merged