New Sample: Create and edit mobilegeodatabases
Esri/arcgis-runtime-samples-android pull request #987
Opened 2022-06-09 23:53 UTC by shubham7109

2022-06-09 23:58 UTC, shubham7109 commented on kotlin/create-and-edit-mobile-geodatabases/src/main/java/com/esri/arcgisruntime/sample/createandeditmobilegeodatabases/MainActivity.kt
> +            Log.e(TAG, "Added feature to table, size = ${featureTable!!.totalFeatureCount}")
Here we have a sample app that creates a geodatabase and adds features to the table. 
Issue:  
I'm not able to see the feature being added to the table here. The total feature count returns 0 always.

2022-06-14 14:09 UTC, TADraeseke requested changes
Nice work @shubham7109!

At review tomorrow can you talk us through the end point of ending at a sharing Intent? Seems a cool idea, I wonder if writing to the app's scoped storage is to restrictive?

Do we want to include the ability to load a new layer from newly made geodatabase or is that too contrived?

Other than that just highlighted some small stuff below.

Also, we'll need a landscape screenshot as normal.

Nice job!

2022-06-14 14:09 UTC, TADraeseke commented on kotlin/create-mobile-geodatabase/src/main/java/com/esri/arcgisruntime/sample/createmobilegeodatabase/MainActivity.kt
> +import android.annotation.SuppressLint
```suggestion
```

2022-06-14 14:09 UTC, TADraeseke commented on kotlin/create-mobile-geodatabase/src/main/java/com/esri/arcgisruntime/sample/createmobilegeodatabase/MainActivity.kt
> +    @SuppressLint("ClickableViewAccessibility")
remove

2022-06-14 14:09 UTC, TADraeseke commented on kotlin/create-mobile-geodatabase/src/main/java/com/esri/arcgisruntime/sample/createmobilegeodatabase/MainActivity.kt
> +    @SuppressLint("SetTextI18n")
remove

2022-06-14 21:23 UTC, shubham7109 commented on kotlin/create-mobile-geodatabase/src/main/java/com/esri/arcgisruntime/sample/createmobilegeodatabase/MainActivity.kt
> +        }
Do you mean something like this?
- displayTable()
    - inflate and attatch layout with ViewBinding
    -  add `viewTableButton.setOnClickListener { show() }`

I would be against doing this as we have to inflate the layout multiple times on each button press and add newer table layout rows as features are added to the map.

2022-06-15 19:38 UTC, shubham7109 commented
At review tomorrow can you talk us through the end point of ending at a sharing Intent? Seems a cool idea, I wonder if writing to the app's scoped storage is to restrictive?

- Let's leave it for the user to decide on how to handle the file by adding permissions to write to external storage. The sharing intent is helpful to share the file out of the device to another using Bluetooth/Email/Drive etc, which seems more aligned with the workflow of mobile geodatabases. 

Do we want to include the ability to load a new layer from newly made geodatabase or is that too contrived?
- This could be a feature in a future sample "Edit Mobile Geodatabases" sample, where layers could be added/removed from a geodatabase file.

2022-06-15 23:52 UTC, saratchandrakarumuri approved these changes
Sample is working as expected

2022-06-17 10:30 UTC, TADraeseke commented on kotlin/create-mobile-geodatabase/src/main/java/com/esri/arcgisruntime/sample/createmobilegeodatabase/MainActivity.kt
> +        }
Nevermind looks like the method's been deprecated and the practice is out of favor. Used to be able to add `android:onClick="methodName"` to xml buttons to call a specific method.

No worries, you're code is totally valid (and better practice!)

2022-06-17 10:47 UTC, TADraeseke approved these changes
Great work @shubham7109. Good use case and very clean code 🎉 

I've left a few small comments below to be addressed before you merge please. I'll approve now though, so I don't hold things up.

Thanks!

2022-06-17 10:47 UTC, TADraeseke commented on kotlin/create-mobile-geodatabase/src/main/java/com/esri/arcgisruntime/sample/createmobilegeodatabase/MainActivity.kt
> +            this.map = ArcGISMap(BasemapStyle.ARCGIS_TOPOGRAPHIC)
```suggestion
            map = ArcGISMap(BasemapStyle.ARCGIS_TOPOGRAPHIC)
```

2022-06-17 10:47 UTC, TADraeseke commented on kotlin/create-mobile-geodatabase/src/main/java/com/esri/arcgisruntime/sample/createmobilegeodatabase/MainActivity.kt
> +
remove whitespace

2022-06-17 10:47 UTC, TADraeseke commented on kotlin/create-mobile-geodatabase/src/main/java/com/esri/arcgisruntime/sample/createmobilegeodatabase/MainActivity.kt
> +
maybe better to extracted to it's own function called "resetMap" or something

2022-06-17 10:47 UTC, TADraeseke commented on kotlin/create-mobile-geodatabase/src/main/res/xml/provider.xml
> +</paths>
missing return at end of file

2022-06-17 17:51 UTC, merged